# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        exclude: |
          (?x)^(
              .*/migrations/.* |
              .*/__init__.py
          )$
        files: market_maker
        args: [ --max-line-length=120 ]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        exclude: |
          (?x)^(
              .*/migrations/.*
          )$
        args: [ --known-local-folder=/, --line-length=120, --profile=black ]

  - repo: https://github.com/ambv/black
    rev: 22.10.0
    hooks:
      - id: black
        args: [ --config=./pyproject.toml ]
        exclude: migrations
  - repo: https://github.com/rtts/djhtml
    rev: v1.5.2
    hooks:
      - id: djhtml
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
    - id: prettier
      types_or: [css, javascript]
      args: [ --use-tabs ]
