version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/app/items
    ports:
      - "8000:8000"
    environment:
      POSTGRES_HOST: db
    env_file:
      - .env
    container_name: items_app
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: items
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: pg_isready -U postgres
      timeout: 20s
      retries: 3
    container_name: items_db
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: