# Generated by Django 4.1.6 on 2023-02-14 18:30

from django.db import migrations, models
import items.models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, validators=[items.models.validate_min]
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="currency",
            field=models.CharField(
                choices=[("usd", "USD"), ("cad", "CAD")], default="cad", max_length=3
            ),
        ),
    ]
